/* ═══════════════════════════════════════════════════
   JAV Manager — Frontend Application
   Data source: data.js (generated by scan.py)
   Javbus info: direct iframe — no server needed
   ═══════════════════════════════════════════════════ */

'use strict';


// ─────────────────────────────────────────────
// State
// ─────────────────────────────────────────────

let appData        = null;
let allItems       = [];
let filteredItems  = [];
let markedItems    = new Set();
let multiSelected  = new Set();   // paths currently multi-selected
let lastMultiIndex = -1;          // index in filteredItems of last Ctrl/Shift click
let currentView    = 'dashboard';
let viewScrollTop  = {};
let selectedItem   = null;
let countChart     = null;
let sizeChart      = null;
let seriesSortKey  = 'count';
let seriesSortAsc  = false;

// ── Lazy-loading (Browse + Classifier) ───────────────────────────────
const BROWSE_PAGE    = 15;   // items rendered per batch
let   browseOffset   = 0;
let   browseObserver = null;
let   clOffset       = 0;
let   clObserver     = null;
let actressAvatars = {};     // name → avatar URL (from data.js, MetaTube/Gfriends)

// ── Statistics dimension (Series code / Maker / Label / Genre / …) ───
let statDim = 'series';

const STAT_DIMS = {
  series:   { label: 'Series (code)',   field: 'series',   get: i => i.series   ? [i.series]   : [] },
  maker:    { label: 'Maker',           field: 'maker',    get: i => i.maker    ? [i.maker]    : [] },
  label:    { label: 'Label',           field: 'label',    get: i => i.label    ? [i.label]    : [] },
  genre:    { label: 'Genre',           field: 'genre',    get: i => i.genres || [] },
  mseries:  { label: 'Series (meta)',   field: 'mseries',  get: i => i.m_series ? [i.m_series] : [] },
  director: { label: 'Director',        field: 'director', get: i => i.director ? [i.director] : [] },
};

// ── Actress grid lazy-loading ─────────────────────────────────────────
const ACTRESS_PAGE  = 40;
let   actressOffset = 0;
let   actressObserver = null;

// ── Classifier state ──────────────────────────
let classifyMap    = {};     // path → category (from classify_data.js)
let clOverrides    = {};     // path → category (session-only manual overrides)
let currentClCat   = 'all';
let hasClassifyData = false;
let clModel        = '—';
let clTime         = '';

const CL_CATS  = ['all','jav','uncensored','hentai','amateur','western',
                   'anime','gravure','game','other','unclassified'];
const CL_ICONS = { jav:'🎌', uncensored:'🔓', hentai:'🌸', amateur:'📱',
                   western:'🌎', anime:'✨', gravure:'📸', game:'🎮',
                   other:'📦', unclassified:'❓' };
const CL_COLORS = { jav:'#f06292', uncensored:'#ff7043', hentai:'#ba68c8',
                    amateur:'#26a69a', western:'#42a5f5', anime:'#e040fb',
                    gravure:'#ec407a', game:'#26c6da', other:'#90a4ae',
                    unclassified:'#546e7a' };
// Categories available for manual override cycling (not 'all' or 'unclassified')
const CL_CYCLE = ['jav','uncensored','hentai','amateur','western','anime','gravure','game','other'];


// ─────────────────────────────────────────────
// Bootstrap
// ─────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', init);

function init() {
  if (localStorage.getItem('sidebarCollapsed') === '1') {
    document.getElementById('sidebar').classList.add('collapsed');
  }

  if (window.__javData__) {
    appData = window.__javData__;
    onDataReady();
  } else {
    // data.js not loaded — user needs to run scan.py first
    el('loading').classList.add('hidden');
    el('error-msg').classList.remove('hidden');
  }
}

function reloadData() {
  window.location.reload();
}

function toggleSidebar() {
  const sidebar = document.getElementById('sidebar');
  const isNowCollapsed = sidebar.classList.toggle('collapsed');
  localStorage.setItem('sidebarCollapsed', isNowCollapsed ? '1' : '0');
}

function onDataReady() {
  allItems       = appData.items || [];
  actressAvatars = appData.actresses || {};

  const s = appData.statistics || {};
  setText('scan-time',  fmtDate(appData.scan_time));
  setText('total-size', s.total_size_human || '?');
  setText('total-dirs', s.total_items || '?');

  const nonjav = allItems.filter(i => !i.is_jav).length;
  const badge = el('nonjav-badge');
  if (nonjav > 0) { badge.textContent = nonjav; badge.style.display = ''; }
  else { badge.style.display = 'none'; }

  // Actress badge — show unique actress count
  const actressSet = new Set();
  allItems.forEach(i => (i.actresses || []).forEach(a => actressSet.add(a)));
  const actressBadge = el('actress-badge');
  if (actressBadge && actressSet.size > 0) {
    actressBadge.textContent = actressSet.size;
    actressBadge.style.display = '';
  }

  // Classifier badge — count unclassified items (only if classify data is loaded)
  const classifyData = window.__classifyData__;
  if (classifyData?.classifications) {
    hasClassifyData = true;
    classifyMap     = classifyData.classifications;
    clModel         = classifyData.model || '—';
    clTime          = classifyData.classified_time || '';
    const unclassified = allItems.filter(i => !classifyMap[i.path]).length;
    const clBadge = el('cl-badge');
    if (clBadge) {
      if (unclassified > 0) { clBadge.textContent = unclassified + ' ?'; clBadge.style.display = ''; }
      else { clBadge.style.display = 'none'; }
    }
  } else {
    // No classify data — show '!' badge to indicate action needed
    const clBadge = el('cl-badge');
    if (clBadge) { clBadge.textContent = '!'; clBadge.style.display = ''; }
  }

  // Delegated click for actress-link tags (handles both cards and detail panel)
  document.addEventListener('click', e => {
    const tag = e.target.closest('.actress-link');
    if (!tag) return;
    e.stopPropagation();
    const name = tag.dataset.actress;
    if (name) filterByActress(name);
  }, true);   // capture phase so it fires before card's own listener

  // Delegated click for metadata chips (maker / label / genre / series / director)
  document.addEventListener('click', e => {
    const chip = e.target.closest('.chip-link');
    if (!chip) return;
    e.stopPropagation();
    const { field, value } = chip.dataset;
    if (field && value) searchByField(field, value);
  }, true);

  el('loading').classList.add('hidden');
  showView(currentView || 'dashboard');
}


// ─────────────────────────────────────────────
// View management
// ─────────────────────────────────────────────

function hideAllViews() {
  document.querySelectorAll('.view').forEach(v => v.classList.add('hidden'));
}

function mainScrollEl() {
  return el('main') || document.scrollingElement || document.documentElement;
}

function rememberViewScroll(name) {
  if (!name) return;
  viewScrollTop[name] = mainScrollEl().scrollTop || 0;
}

function restoreViewScroll(name) {
  const top = viewScrollTop[name];
  if (top === undefined) return;

  requestAnimationFrame(() => {
    mainScrollEl().scrollTop = top;
  });
}

function showView(name) {
  if (currentView && currentView !== name) rememberViewScroll(currentView);

  hideAllViews();
  currentView = name;
  lastMultiIndex = -1;   // indices are view-specific; reset on tab switch

  const viewEl = el(`view-${name}`);
  if (viewEl) viewEl.classList.remove('hidden');

  document.querySelectorAll('.nav-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.view === name);
  });

  if      (name === 'dashboard')  renderDashboard();
  else if (name === 'browse')     renderBrowse();
  else if (name === 'statistics') renderStatistics();
  else if (name === 'actress')    renderActress();
  else if (name === 'classifier') renderClassifier();
  else if (name === 'nonjav')     renderNonJav();

  if (name === 'actress') restoreViewScroll(name);
}


// ─────────────────────────────────────────────
// Dashboard
// ─────────────────────────────────────────────

function renderDashboard() {
  if (!appData) return;
  const s = appData.statistics || {};

  setText('s-total',  s.total_items   || 0);
  setText('s-jav',    s.jav_count     || 0);
  setText('s-nonjav', s.non_jav_count || 0);
  setText('s-size',   s.total_size_human || '?');
  setText('s-series', Object.keys(s.series_count || {}).length);

  const countEntries = Object.entries(s.series_count || {}).slice(0, 20);
  renderBarChart('chart-count', countEntries.map(([k]) => k),
    countEntries.map(([, v]) => v), '# videos', countEntries.map(([k]) => k));

  const sizeData    = s.series_size || {};
  const sizeEntries = Object.entries(sizeData)
    .sort((a, b) => b[1].size - a[1].size).slice(0, 20);
  renderBarChart('chart-size', sizeEntries.map(([k]) => k),
    sizeEntries.map(([, v]) => +(v.size / 1e9).toFixed(1)), 'GB',
    sizeEntries.map(([k]) => k));

  // Maker / Genre charts — computed client-side from MetaTube metadata
  const makerRows = buildDimStats('maker')
    .sort((a, b) => b.count - a.count).slice(0, 20);
  renderBarChart('chart-maker', makerRows.map(r => r.series),
    makerRows.map(r => r.count), '# videos', makerRows.map(r => r.series));

  const genreRows = buildDimStats('genre')
    .sort((a, b) => b.count - a.count).slice(0, 20);
  renderBarChart('chart-genre', genreRows.map(r => r.series),
    genreRows.map(r => r.count), '# videos', genreRows.map(r => r.series));
}

function renderBarChart(canvasId, labels, values, unit, colorKeys) {
  const canvas = el(canvasId);
  if (!canvas) return;

  const existing = Chart.getChart(canvas);
  if (existing) existing.destroy();

  // Fix explicit pixel size — prevents Chart.js responsive resize loop
  const w = canvas.parentElement.clientWidth || 500;
  const h = Math.max(260, labels.length * 28);
  canvas.width  = w;
  canvas.height = h;
  canvas.style.width  = w + 'px';
  canvas.style.height = h + 'px';

  new Chart(canvas, {
    type: 'bar',
    data: {
      labels,
      datasets: [{
        data:            values,
        backgroundColor: colorKeys.map(k => seriesColor(k, 0.65)),
        borderColor:     colorKeys.map(k => seriesColor(k, 1)),
        borderWidth: 1,
      }],
    },
    options: {
      animation: false,
      responsive: false,
      indexAxis: 'y',
      plugins: {
        legend: { display: false },
        tooltip: { callbacks: { label: ctx => ` ${ctx.raw} ${unit}` } },
      },
      scales: {
        x: { beginAtZero: true,
             ticks: { color: '#7070a0', font: { size: 11 } },
             grid:  { color: '#2a2a50' } },
        y: { ticks: { color: '#e0e0f0', font: { size: 11 } },
             grid:  { display: false } },
      },
    },
  });
}


// ─────────────────────────────────────────────
// Browse
// ─────────────────────────────────────────────

function renderBrowse() { applyFilters(); }

// ── Field-scoped search ─────────────────────────────────────────────
// Supports tokens like  maker:S1  label:"S1 NO.1 STYLE"  genre:単体作品
// actress:JULIA  series:MIDE  mseries:...  director:...  provider:JavBus
// Remaining free text matches across every metadata field.
const FIELD_GETTERS = {
  maker:    i => i.maker || '',
  label:    i => i.label || '',
  genre:    i => (i.genres || []).join('\n'),
  genres:   i => (i.genres || []).join('\n'),
  actress:  i => (i.actresses || []).join('\n'),
  series:   i => i.series || '',           // bango prefix (MIDE, SSNI, …)
  mseries:  i => i.m_series || '',         // metadata series name
  director: i => i.director || '',
  provider: i => i.meta_provider || '',
  bango:    i => i.bango || '',
  title:    i => i.title || '',
};

function parseQuery(raw) {
  const fields = [];
  const free = raw.replace(/([a-z]+):"([^"]*)"|([a-z]+):(\S+)/gi, (m, f1, v1, f2, v2) => {
    const f = (f1 || f2).toLowerCase();
    if (FIELD_GETTERS[f]) { fields.push([f, (v1 ?? v2).toLowerCase()]); return ' '; }
    return m;   // unknown prefix — treat as free text
  }).trim().toLowerCase();
  return { fields, free };
}

function itemMatchesQuery(item, q) {
  for (const [f, v] of q.fields) {
    if (!FIELD_GETTERS[f](item).toLowerCase().includes(v)) return false;
  }
  if (q.free) {
    const hay = (item.name + ' ' + (item.bango || '') + ' ' + (item.title || '') + ' ' +
                 (item.actresses || []).join(' ') + ' ' + (item.maker || '') + ' ' +
                 (item.label || '') + ' ' + (item.m_series || '') + ' ' +
                 (item.genres || []).join(' ') + ' ' + (item.director || '')).toLowerCase();
    return hay.includes(q.free);
  }
  return true;
}

// ── MetaTube image proxy fallback ───────────────────────────────────
// Images load directly from the original hosts (DMM/MGS…). Only when a host
// blocks hotlinking (JavBus-only titles) do we retry once through the
// MetaTube server's public /v1/images endpoint.
function mtImageUrl(item, kind) {   // kind: 'thumb' | 'primary' | 'backdrop'
  const base = appData?.metatube_url;
  if (!base || !item.meta_provider || !item.provider_id) return '';
  return `${base}/v1/images/${kind}/` +
         `${encodeURIComponent(item.meta_provider)}/${encodeURIComponent(item.provider_id)}`;
}

// Inline onerror handler for detail-panel images (cover / previews)
function imgFallback(img) {
  const fb = img.dataset.fbUrl;
  if (fb && !img.dataset.fb) { img.dataset.fb = '1'; img.src = fb; }
  else img.style.display = 'none';
}

// Jump to Browse pre-filtered on one metadata field (used by all chips)
function searchByField(field, value) {
  el('search-box').value = /\s/.test(value) ? `${field}:"${value}"` : `${field}:${value}`;
  el('jav-only').checked = false;
  showView('browse');
}

function applyFilters() {
  if (!allItems.length) return;

  const rawQuery = (el('search-box')?.value  || '').trim();
  const sort     = el('sort-select')?.value  || 'size-desc';
  const javOnly  = el('jav-only')?.checked   || false;
  const q        = parseQuery(rawQuery);

  let items = allItems.filter(item => {
    if (javOnly && !item.is_jav) return false;
    if (rawQuery) return itemMatchesQuery(item, q);
    return true;
  });

  items.sort((a, b) => {
    switch (sort) {
      case 'size-desc':  return b.total_size - a.total_size;
      case 'size-asc':   return a.total_size - b.total_size;
      case 'date-desc':  return (b.release_date || '').localeCompare(a.release_date || '');
      case 'date-asc':   return (a.release_date || '9999').localeCompare(b.release_date || '9999');
      case 'score-desc': return (b.score || 0) - (a.score || 0);
      case 'name-asc':   return a.name.localeCompare(b.name);
      case 'name-desc':  return b.name.localeCompare(a.name);
      case 'series-asc': return (a.series || 'zzz').localeCompare(b.series || 'zzz');
      default:           return 0;
    }
  });

  filteredItems = items;
  setText('result-count', items.length);
  setText('result-size', bytesToHuman(items.reduce((s, i) => s + (i.total_size || 0), 0)));
  renderItemList(items, 'item-list');
}

function disconnectBrowseObserver() {
  if (browseObserver) { browseObserver.disconnect(); browseObserver = null; }
}

function disconnectClObserver() {
  if (clObserver) { clObserver.disconnect(); clObserver = null; }
}

function renderItemList(items, containerId) {
  const container = el(containerId);
  if (!container) return;

  // Non-browse containers (nonjav-list etc.): render everything at once
  if (containerId !== 'item-list') {
    const frag = document.createDocumentFragment();
    items.forEach((item, idx) => frag.appendChild(createItemCard(item, idx)));
    container.innerHTML = '';
    container.appendChild(frag);
    return;
  }

  // Browse: render in pages, load next page when sentinel scrolls into view
  disconnectBrowseObserver();
  browseOffset = 0;
  container.innerHTML = '';

  function appendNextPage() {
    const end  = Math.min(browseOffset + BROWSE_PAGE, items.length);
    const frag = document.createDocumentFragment();
    for (let i = browseOffset; i < end; i++) {
      frag.appendChild(createItemCard(items[i], i));
    }
    browseOffset = end;

    // Remove stale sentinel before appending new items
    const old = container.querySelector('.browse-sentinel');
    if (old) old.remove();

    container.appendChild(frag);

    if (browseOffset < items.length) {
      // Add a sentinel div that triggers the next page when it nears the viewport
      const sentinel = document.createElement('div');
      sentinel.className = 'browse-sentinel';
      container.appendChild(sentinel);

      browseObserver = new IntersectionObserver(entries => {
        if (entries[0].isIntersecting) {
          disconnectBrowseObserver();
          appendNextPage();
        }
      }, { rootMargin: '300px' });   // start loading 300px before sentinel is visible
      browseObserver.observe(sentinel);
    }
  }

  appendNextPage();
}

function createItemCard(item, idx = -1) {
  const isMarked      = markedItems.has(item.path);
  const isSelected    = selectedItem && selectedItem.path === item.path;
  const isMultiSelect = multiSelected.has(item.path);

  const card = document.createElement('div');
  card.className = 'item-card' +
    (isSelected    ? ' is-selected'      : '') +
    (isMarked      ? ' is-marked'        : '') +
    (isMultiSelect ? ' is-multi-selected': '');
  card.dataset.path = item.path;

  // Checkbox for multi-select
  const checkCol = document.createElement('div');
  checkCol.className = 'item-check-col';
  const checkbox = document.createElement('input');
  checkbox.type    = 'checkbox';
  checkbox.className = 'item-check';
  checkbox.checked = isMultiSelect;
  checkbox.addEventListener('click', e => {
    e.stopPropagation();
    handleMultiClick(item, idx, e.shiftKey);
  });
  checkCol.appendChild(checkbox);
  card.appendChild(checkCol);

  // Cover thumbnail (embedded from metadata) — takes the full left slot
  if (item.cover) {
    const thumb = document.createElement('img');
    thumb.className = 'item-thumb';
    thumb.src = item.thumb || item.cover;
    thumb.alt = '';
    thumb.loading = 'lazy';
    thumb.referrerPolicy = 'no-referrer';   // bypass hotlink protection on image hosts
    thumb.onerror = function() {
      // Hotlink blocked → retry once via the MetaTube image proxy
      const fb = mtImageUrl(item, 'thumb');
      if (fb && !this.dataset.fb) { this.dataset.fb = '1'; this.src = fb; }
      else this.style.display = 'none';
    };
    card.appendChild(thumb);
  }

  // Info — show javbus title if available, folder name as fallback/tooltip
  const actressHtml = item.actresses?.length
    ? `<div class="item-actresses">` +
      item.actresses.slice(0, 3).map(a =>
        `<span class="actress-tag actress-link" data-actress="${esc(a)}" title="Browse ${esc(a)}">${esc(a)}</span>`
      ).join('') +
      (item.actresses.length > 3
        ? `<span class="actress-tag" title="${item.actresses.slice(3).map(a => esc(a)).join(', ')}">+${item.actresses.length - 3}</span>`
        : '') +
      `</div>`
    : '';

  // Metadata chip row: release date · maker · label · score
  const chips = [];
  if (item.release_date) chips.push(`<span class="meta-chip chip-date">📅 ${esc(item.release_date)}</span>`);
  if (item.maker)  chips.push(`<span class="meta-chip chip-link" data-field="maker" data-value="${esc(item.maker)}" title="Browse maker">🏭 ${esc(item.maker)}</span>`);
  if (item.label)  chips.push(`<span class="meta-chip chip-link" data-field="label" data-value="${esc(item.label)}" title="Browse label">🏷️ ${esc(item.label)}</span>`);
  if (item.score)  chips.push(`<span class="meta-chip chip-score">★ ${(+item.score).toFixed(1)}</span>`);
  const chipHtml = chips.length ? `<div class="item-chips">${chips.join('')}</div>` : '';

  const info = document.createElement('div');
  info.className = 'item-info';
  info.innerHTML = `
    <div class="item-bango">${esc(item.bango || '(no bango)')}</div>
    <div class="item-name" title="${esc(item.name)}">${esc(item.title || item.name)}</div>
    <div class="item-meta">${item.file_count} file(s) · ${item.video_count} video(s)</div>
    ${chipHtml}
    ${actressHtml}
  `;
  card.appendChild(info);

  // Size
  const sizeEl = document.createElement('div');
  sizeEl.className = 'item-size';
  sizeEl.textContent = item.total_size_human || '?';
  card.appendChild(sizeEl);

  // Mark button
  const markBtn = document.createElement('button');
  markBtn.className   = 'mark-btn' + (isMarked ? ' marked' : '');
  markBtn.textContent = isMarked ? '🗑️ Marked' : '🗑️ Mark';
  markBtn.onclick = e => {
    e.stopPropagation();
    toggleMark(item);
    const marked = markedItems.has(item.path);
    markBtn.className   = 'mark-btn' + (marked ? ' marked' : '');
    markBtn.textContent = marked ? '🗑️ Marked' : '🗑️ Mark';
    card.classList.toggle('is-marked', marked);
    if (selectedItem?.path === item.path) updateDetailMarkBtn();
  };
  card.appendChild(markBtn);

  card.addEventListener('click', () => openDetail(item));
  return card;
}


// ─────────────────────────────────────────────
// Statistics
// ─────────────────────────────────────────────

// Aggregate items along one metadata dimension (maker / label / genre / …)
function buildDimStats(dim) {
  const get = STAT_DIMS[dim].get;
  const map = {};
  allItems.forEach(item => {
    if (!item.is_jav) return;
    get(item).forEach(key => {
      if (!map[key]) map[key] = { count: 0, size: 0 };
      map[key].count++;
      map[key].size += item.total_size || 0;
    });
  });
  return Object.entries(map).map(([key, d]) => ({
    series: key, count: d.count, size: d.size, size_human: bytesToHuman(d.size),
  }));
}

function buildStatDimBar() {
  const bar = el('stat-dim-bar');
  if (!bar) return;
  bar.innerHTML = '';
  Object.entries(STAT_DIMS).forEach(([dim, def]) => {
    const pill = document.createElement('button');
    pill.className = 'cat-pill' + (dim === statDim ? ' active' : '');
    pill.textContent = def.label;
    pill.onclick = () => { statDim = dim; renderStatistics(); };
    bar.appendChild(pill);
  });
}

function renderStatistics() {
  if (!appData) return;
  buildStatDimBar();
  const colHeader = el('stat-dim-col');
  if (colHeader) colHeader.textContent = STAT_DIMS[statDim].label;

  let rows = buildDimStats(statDim);

  rows.sort((a, b) => {
    let cmp = 0;
    if      (seriesSortKey === 'series') cmp = a.series.localeCompare(b.series, 'ja');
    else if (seriesSortKey === 'count')  cmp = a.count - b.count;
    else if (seriesSortKey === 'size')   cmp = a.size  - b.size;
    return seriesSortAsc ? cmp : -cmp;
  });

  const field = STAT_DIMS[statDim].field;
  const tbody = el('series-body');
  tbody.innerHTML = '';

  rows.forEach((row, idx) => {
    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td class="rank-cell">${idx + 1}</td>
      <td class="series-cell">
        <span style="display:inline-block;width:10px;height:10px;border-radius:3px;
          background:${seriesColor(row.series)};margin-right:7px;vertical-align:middle"></span>
        ${esc(row.series)}
      </td>
      <td class="count-cell">${row.count}</td>
      <td class="size-cell">${row.size_human}</td>
    `;
    tr.style.cursor = 'pointer';
    tr.title = `Click to browse ${row.series}`;
    tr.addEventListener('click', () => searchByField(field, row.series));
    tbody.appendChild(tr);
  });
}

function sortSeriesTable(key) {
  if (seriesSortKey === key) seriesSortAsc = !seriesSortAsc;
  else { seriesSortKey = key; seriesSortAsc = false; }
  renderStatistics();
}


// ─────────────────────────────────────────────
// Actresses
// ─────────────────────────────────────────────

function buildActressStats() {
  const map = {};
  allItems.forEach(item => {
    (item.actresses || []).forEach(a => {
      if (!map[a]) map[a] = { count: 0, size: 0, makers: {}, genres: {} };
      const d = map[a];
      d.count++;
      d.size += item.total_size || 0;
      if (item.maker) d.makers[item.maker] = (d.makers[item.maker] || 0) + 1;
      (item.genres || []).forEach(g => { d.genres[g] = (d.genres[g] || 0) + 1; });
    });
  });
  const top = obj => Object.entries(obj).sort((a, b) => b[1] - a[1]).slice(0, 2).map(e => e[0]);
  return Object.entries(map).map(([name, d]) => ({
    name,
    count:      d.count,
    size:       d.size,
    size_human: bytesToHuman(d.size),
    avatar:     actressAvatars[name] || '',
    topMakers:  top(d.makers),
    topGenres:  top(d.genres),
  }));
}

function disconnectActressObserver() {
  if (actressObserver) { actressObserver.disconnect(); actressObserver = null; }
}

function createActressCard(row) {
  const card = document.createElement('div');
  card.className = 'actress-card';
  card.title = `Browse items by ${row.name}`;

  const avatarHtml = row.avatar
    ? `<img class="actress-avatar" src="${esc(row.avatar)}" alt="" loading="lazy"
         referrerpolicy="no-referrer"
         onerror="this.outerHTML='<div class=&quot;actress-avatar placeholder&quot;>👤</div>'">`
    : `<div class="actress-avatar placeholder">👤</div>`;

  const makerHtml = row.topMakers.length
    ? `<div class="actress-sub" title="${esc(row.topMakers.join(', '))}">🏭 ${esc(row.topMakers.join(' · '))}</div>` : '';
  const genreHtml = row.topGenres.length
    ? `<div class="actress-sub" title="${esc(row.topGenres.join(', '))}">🏷️ ${esc(row.topGenres.join(' · '))}</div>` : '';

  card.innerHTML = `
    ${avatarHtml}
    <div class="actress-card-name">${esc(row.name)}</div>
    <div class="actress-card-stats">${row.count} item${row.count > 1 ? 's' : ''} · ${row.size_human}</div>
    ${makerHtml}
    ${genreHtml}
  `;
  card.addEventListener('click', () => filterByActress(row.name));
  return card;
}

function renderActress() {
  let rows = buildActressStats();

  const sort = el('actress-sort')?.value || 'count-desc';
  rows.sort((a, b) => {
    switch (sort) {
      case 'size-desc': return b.size - a.size;
      case 'name-asc':  return a.name.localeCompare(b.name, 'ja');
      default:          return b.count - a.count;
    }
  });

  const query = (el('actress-search')?.value || '').toLowerCase().trim();
  if (query) rows = rows.filter(r => r.name.toLowerCase().includes(query));

  const withAvatar = rows.filter(r => r.avatar).length;
  setText('actress-result-count', `${rows.length} actresses · ${withAvatar} with photo`);

  const grid = el('actress-grid');
  if (!grid) return;

  // Lazy-render in pages (same pattern as Browse)
  disconnectActressObserver();
  actressOffset = 0;
  grid.innerHTML = '';

  function appendNextPage() {
    const end  = Math.min(actressOffset + ACTRESS_PAGE, rows.length);
    const frag = document.createDocumentFragment();
    for (let i = actressOffset; i < end; i++) frag.appendChild(createActressCard(rows[i]));
    actressOffset = end;

    const old = grid.querySelector('.browse-sentinel');
    if (old) old.remove();

    grid.appendChild(frag);

    if (actressOffset < rows.length) {
      const sentinel = document.createElement('div');
      sentinel.className = 'browse-sentinel';
      grid.appendChild(sentinel);
      actressObserver = new IntersectionObserver(entries => {
        if (entries[0].isIntersecting) {
          disconnectActressObserver();
          appendNextPage();
        }
      }, { rootMargin: '400px' });
      actressObserver.observe(sentinel);
    }
  }

  appendNextPage();

  // If we're returning to this tab with a saved scroll position, the lazily
  // rendered first page may be too short for the browser to scroll back to it.
  // Synchronously append pages until the content is tall enough.
  const savedTop = viewScrollTop['actress'];
  if (savedTop) {
    const scroller = mainScrollEl();
    while (actressOffset < rows.length &&
           scroller.scrollHeight < savedTop + scroller.clientHeight) {
      disconnectActressObserver();
      appendNextPage();
    }
  }
}

function filterByActress(name) {
  searchByField('actress', name);
}


// ─────────────────────────────────────────────
// Non-JAV
// ─────────────────────────────────────────────

function renderNonJav() {
  const items = allItems.filter(i => !i.is_jav);
  filteredItems = items;
  const totalBytes = items.reduce((sum, i) => sum + (i.total_size || 0), 0);
  const humanSize = appData?.statistics?.total_size_human
    ? (() => {
        // reuse the same formatting logic
        let b = totalBytes;
        for (const u of ['B','KB','MB','GB','TB']) {
          if (b < 1024) return b.toFixed(1) + ' ' + u;
          b /= 1024;
        }
        return b.toFixed(1) + ' PB';
      })()
    : '?';
  setText('nonjav-size', `${items.length} items · ${humanSize}`);
  renderItemList(items, 'nonjav-list');
}


// ─────────────────────────────────────────────
// Detail panel
// ─────────────────────────────────────────────

function openDetail(item) {
  selectedItem = item;
  document.querySelectorAll('.item-card').forEach(c =>
    c.classList.toggle('is-selected', c.dataset.path === item.path)
  );
  el('detail-panel').classList.remove('hidden');
  renderDetailShell(item);
}

function closeDetail() {
  el('detail-panel').classList.add('hidden');
  closeJavbus();
  selectedItem = null;
  document.querySelectorAll('.item-card.is-selected')
    .forEach(c => c.classList.remove('is-selected'));
}

// One clickable field row for the detail metadata table ('' → hidden)
function detailRow(label, value, field) {
  if (!value) return '';
  const v = field
    ? `<span class="chip-link detail-field-link" data-field="${field}" data-value="${esc(value)}"
         title="Browse ${label.toLowerCase()}">${esc(value)}</span>`
    : esc(value);
  return `<div class="detail-meta-row"><span class="dm-label">${label}</span><span class="dm-value">${v}</span></div>`;
}

function renderDetailShell(item) {
  const isMarked = markedItems.has(item.path);

  // Build metadata block from embedded fields (populated by scan.py via MetaTube)
  let metaHtml = '';
  if (item.is_jav && (item.cover || item.title || item.actresses?.length)) {
    const actressHtml = item.actresses?.length
      ? `<div class="jav-actresses">👤 ${item.actresses.map(a =>
          `<span class="actress-tag actress-link" data-actress="${esc(a)}" title="Browse ${esc(a)}">${esc(a)}</span>`
        ).join('')}</div>`
      : '';

    const genreHtml = item.genres?.length
      ? `<div class="detail-genres">${item.genres.map(g =>
          `<span class="genre-tag chip-link" data-field="genre" data-value="${esc(g)}" title="Browse genre">${esc(g)}</span>`
        ).join('')}</div>`
      : '';

    const scoreStr   = item.score ? `${'★'.repeat(Math.round(item.score / 2))} ${(+item.score).toFixed(1)}` : '';
    const runtimeStr = item.runtime ? `${item.runtime} min` : '';

    const metaRows = [
      detailRow('Released', item.release_date),
      detailRow('Runtime',  runtimeStr),
      detailRow('Maker',    item.maker,    'maker'),
      detailRow('Label',    item.label,    'label'),
      detailRow('Series',   item.m_series, 'mseries'),
      detailRow('Director', item.director, 'director'),
      detailRow('Score',    scoreStr),
    ].join('');

    const sourceHtml = item.homepage
      ? `<div class="detail-meta-row"><span class="dm-label">Source</span><span class="dm-value">
           <a href="${esc(item.homepage)}" target="_blank" rel="noopener">${esc(item.meta_provider || 'provider page')} ↗</a>
         </span></div>`
      : '';

    const summaryHtml = item.summary
      ? `<details class="detail-summary"><summary>Summary</summary><p>${esc(item.summary)}</p></details>`
      : '';

    const mtBase = mtImageUrl(item, 'backdrop');   // '' when no provider info
    const previewHtml = item.preview_images?.length
      ? `<div class="detail-section-title">Preview images</div>
         <div class="preview-strip">${item.preview_images.map(u =>
           `<img class="preview-thumb" src="${esc(u)}" alt="" loading="lazy"
              referrerpolicy="no-referrer" onclick="openPreviewLightbox(this)"
              data-fb-url="${mtBase ? esc(mtBase + '?url=' + encodeURIComponent(u)) : ''}"
              onerror="imgFallback(this)">`
         ).join('')}</div>`
      : '';

    metaHtml = `
      <div class="jav-info-card">
        ${item.cover ? `<img class="jav-cover" src="${esc(item.cover)}" alt="cover" loading="lazy"
          referrerpolicy="no-referrer"
          data-fb-url="${esc(mtImageUrl(item, 'backdrop'))}"
          style="cursor:zoom-in" onclick="openCoverLightbox(this.src)"
          onerror="imgFallback(this)">` : ''}
        <div class="jav-meta">
          ${item.title ? `<div class="jav-title">${esc(item.title)}</div>` : ''}
          <div class="detail-meta-table">${metaRows}${sourceHtml}</div>
          ${genreHtml}
          ${actressHtml}
          ${summaryHtml}
        </div>
      </div>
      ${previewHtml}`;
  }

  el('detail-body').innerHTML = `
    <div class="detail-bango">${esc(item.bango || '(no bango)')}</div>

    ${metaHtml}

    <div class="detail-section-title">Files on disk</div>
    <div style="font-size:12px;color:var(--text-muted);margin-bottom:8px;">
      <a class="path-link" href="${localUrl(item.path)}" target="_blank" title="Open folder">📁 ${esc(item.name)}</a>
      &nbsp;·&nbsp; ${item.total_size_human} &nbsp;·&nbsp; ${item.file_count} file(s)
    </div>
    <div id="detail-files">${renderFileList(item.path, item.files, item.is_file_item)}</div>
    ${item.file_count > item.files.length
      ? `<div style="font-size:12px;color:var(--text-muted);margin-top:6px;">
           … and ${item.file_count - item.files.length} more in subfolders
         </div>` : ''}

    <div class="detail-actions">
      ${item.bango
        ? `<button class="detail-link-btn" onclick="openJavbus('${esc(item.bango)}')">
             🎬 View on Javbus
           </button>` : ''}
      <button class="detail-mark-btn ${isMarked ? 'unmark' : ''}" id="detail-mark-btn"
        onclick="toggleMarkFromDetail()">
        ${isMarked ? '↩️ Unmark' : '🗑️ Mark for Deletion'}
      </button>
    </div>
  `;
}

function openInPotPlayer(path) {
  if (path.toLowerCase().endsWith('.iso')) {
    // ISO files can't be streamed via CloudDrive; open the local path directly.
    // ISO paths contain no CJK, so the opaque potplayer: scheme (no //) is safe
    // and preserves the drive-letter colon and brackets without Chrome mangling.
    window.location.href = 'potplayer:' + path.replace(/\\/g, '/');
  } else {
    // Build the CloudDrive2 streaming URL the same way the CE115 userscript does.
    // Strip the drive letter, encode the full cloud path (including / → %2F),
    // then hand it to PotPlayer as an HTTP stream — no local path encoding issues.
    const cloudPath = '/' + path.replace(/^[A-Za-z]:\\/, '').replace(/\\/g, '/');
    const cdUrl = `http://localhost:19798/static/http/localhost:19798/False/${encodeURIComponent(cloudPath)}?check_expire=True`;
    window.location.href = 'potplayer://' + cdUrl;
  }
}

const _VIDEO_EXTS = new Set(['.mp4','.mkv','.avi','.wmv','.mov','.m4v','.ts','.m2ts','.iso','.rmvb','.flv','.webm']);

function renderFileList(folderPath, files, isFileItem) {
  if (!files?.length) return '<div class="muted">No files listed</div>';
  return files.map(f => {
    // isFileItem: item.path is the file itself (flat-pack or root-dir direct file).
    // In that case folderPath already IS the full file path; do not append the name.
    // For normal folder items, construct the full path by joining folder + filename.
    const filePath = isFileItem ? folderPath : folderPath + '\\' + f.name;
    const url = localUrl(filePath);
    const ppBtn = _VIDEO_EXTS.has(f.ext)
      ? `<a class="potplayer-btn" href="#"
           onclick="event.preventDefault();openInPotPlayer(this.dataset.path)"
           data-path="${esc(filePath)}">▶ PotPlayer</a>`
      : '';
    return `<div class="file-entry">
       <span>${fileIcon(f.ext)}</span>
       <a class="file-name path-link" href="${url}" target="_blank" title="${esc(f.name)}">${esc(f.name)}</a>
       ${ppBtn}
       <span class="file-size">${f.size_human || ''}</span>
     </div>`;
  }).join('');
}

// Convert a Windows path to an Everything HTTP server URL.
//
// When the page is served over HTTP (e.g. http://192.168.1.101:8080/),
// window.location.hostname IS the PC's IP -- no config.js dependency.
// We build:  E:\115\foo\bar.mp4  ->  http://192.168.1.101/E%3A/115/foo/bar.mp4
// Each path segment is encodeURIComponent'd so spaces, brackets, CJK chars
// and the colon in "E:" are all properly escaped, matching Everything's own links.
//
// The Everything port defaults to 80. If you run Everything on a different port,
// set everythingPort in serve.py (it writes config.js with that value).
//
// Falls back to file:// URLs when opened directly (file:// protocol on PC).
function localUrl(winPath) {
  if (window.location.protocol !== 'file:') {
    const cfg = window.__serverConfig__;
    const everythingPort = (cfg && cfg.everythingPort) || 80;
    const host = window.location.hostname;
    const base = everythingPort === 80
      ? `http://${host}`
      : `http://${host}:${everythingPort}`;
    const encoded = winPath.replace(/\\/g, '/')
                           .split('/')
                           .map(s => encodeURIComponent(s))
                           .join('/');
    return base + '/' + encoded;
  }
  return 'file:///' + winPath.replace(/\\/g, '/');
}

function fileIcon(ext) {
  const VIDEO = new Set(['.mp4','.mkv','.avi','.wmv','.mov','.m4v','.ts','.m2ts','.iso','.rmvb','.flv','.webm']);
  if (VIDEO.has(ext)) return '🎬';
  if (['.jpg','.jpeg','.png','.webp','.avif','.gif','.bmp'].includes(ext)) return '🖼️';
  if (ext === '.nfo') return '📄';
  if (['.srt','.ass','.ssa','.sub'].includes(ext)) return '💬';
  return '📎';
}

function updateDetailMarkBtn() {
  if (!selectedItem) return;
  const btn = el('detail-mark-btn');
  if (!btn) return;
  const marked = markedItems.has(selectedItem.path);
  btn.className   = 'detail-mark-btn' + (marked ? ' unmark' : '');
  btn.textContent = marked ? '↩️ Unmark' : '🗑️ Mark for Deletion';
}


// ─────────────────────────────────────────────
// Cover image lightbox
// ─────────────────────────────────────────────

let lightboxImages = [];   // src list for prev/next navigation
let lightboxIndex  = -1;

function openCoverLightbox(src) {
  lightboxImages = [];
  lightboxIndex  = -1;
  showLightbox(src);
}

// Opened from a preview thumbnail: collect all thumbs in the strip
// so the arrows can step through them.
function openPreviewLightbox(imgEl) {
  const strip = imgEl.closest('.preview-strip');
  const thumbs = strip ? [...strip.querySelectorAll('.preview-thumb')] : [imgEl];
  lightboxImages = thumbs.map(t => t.src);
  lightboxIndex  = thumbs.indexOf(imgEl);
  showLightbox(imgEl.src);
}

function showLightbox(src) {
  const lb  = el('cover-lightbox');
  const img = el('cover-lightbox-img');
  if (!lb || !img) return;
  img.src = src;
  lb.classList.remove('hidden');
  lb.classList.toggle('has-nav', lightboxImages.length > 1);
}

function lightboxStep(delta) {
  if (lightboxImages.length < 2 || lightboxIndex < 0) return;
  lightboxIndex = (lightboxIndex + delta + lightboxImages.length) % lightboxImages.length;
  const img = el('cover-lightbox-img');
  if (img) img.src = lightboxImages[lightboxIndex];
}

function closeCoverLightbox() {
  const lb = el('cover-lightbox');
  if (lb) lb.classList.add('hidden');
}

// Lightbox keyboard: Escape closes, arrows navigate
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') closeCoverLightbox();
  const lb = el('cover-lightbox');
  if (!lb || lb.classList.contains('hidden')) return;
  if (e.key === 'ArrowLeft')  { e.preventDefault(); lightboxStep(-1); }
  if (e.key === 'ArrowRight') { e.preventDefault(); lightboxStep(1); }
});


// ─────────────────────────────────────────────
// Javbus iframe overlay
// ─────────────────────────────────────────────

// Javbus URL slug differs by studio:
//   1PONDO-052611-102     → 052611_102   (underscore)
//   CARIBBEANCOM-102720-001 → 102720-001  (dash)
//   everything else       → bango as-is
function javbusSlug(bango) {
  let m = bango.match(/^1PONDO-(\d{6})-(\d{3})$/i);
  if (m) return `${m[1]}_${m[2]}`;
  m = bango.match(/^(?:CARIBBEANCOM|CARIBPR)-(\d{6})-(\d{3})$/i);
  if (m) return `${m[1]}-${m[2]}`;
  return bango;
}

function openJavbus(bango) {
  const overlay = el('javbus-overlay');
  const iframe  = el('javbus-iframe');
  const bangoEl = el('javbus-bango-label');
  const link    = el('javbus-newtab');

  const slug = javbusSlug(bango);
  const url  = `https://www.javbus.com/${encodeURIComponent(slug)}`;
  if (bangoEl) bangoEl.textContent = bango;
  if (link)    link.href = url;
  iframe.src = url;
  overlay.classList.remove('hidden');
}

function closeJavbus() {
  const overlay = el('javbus-overlay');
  const iframe  = el('javbus-iframe');
  if (!overlay) return;
  overlay.classList.add('hidden');
  iframe.src = '';   // stop loading
}


// ─────────────────────────────────────────────
// Marking
// ─────────────────────────────────────────────

function toggleMark(item) {
  if (markedItems.has(item.path)) markedItems.delete(item.path);
  else markedItems.add(item.path);
  updateMarkedSidebar();
}

function toggleMarkFromDetail() {
  if (!selectedItem) return;
  toggleMark(selectedItem);
  updateDetailMarkBtn();
  const card = document.querySelector(`.item-card[data-path="${CSS.escape(selectedItem.path)}"]`);
  if (card) {
    const marked = markedItems.has(selectedItem.path);
    card.classList.toggle('is-marked', marked);
    const btn = card.querySelector('.mark-btn');
    if (btn) {
      btn.className   = 'mark-btn' + (marked ? ' marked' : '');
      btn.textContent = marked ? '🗑️ Marked' : '🗑️ Mark';
    }
  }
}

function updateMarkedSidebar() {
  const count = markedItems.size;
  const sidebar = el('marked-sidebar');
  el('marked-count').textContent = count;
  sidebar.classList.toggle('hidden', count === 0);
}

function clearMarked() {
  markedItems.clear();
  updateMarkedSidebar();
  document.querySelectorAll('.item-card.is-marked').forEach(c => {
    c.classList.remove('is-marked');
    const btn = c.querySelector('.mark-btn');
    if (btn) { btn.className = 'mark-btn'; btn.textContent = '🗑️ Mark'; }
  });
  updateDetailMarkBtn();
}

// ─────────────────────────────────────────────
// Multi-select
// ─────────────────────────────────────────────

function handleMultiClick(item, idx, isShift) {
  if (isShift && lastMultiIndex >= 0 && idx >= 0) {
    // Range select: add everything from lastMultiIndex to idx
    const from = Math.min(lastMultiIndex, idx);
    const to   = Math.max(lastMultiIndex, idx);
    for (let i = from; i <= to; i++) {
      if (filteredItems[i]) multiSelected.add(filteredItems[i].path);
    }
  } else {
    // Ctrl/⌘: toggle single item
    if (multiSelected.has(item.path)) multiSelected.delete(item.path);
    else                              multiSelected.add(item.path);
    lastMultiIndex = idx;
  }
  updateMultiSelectCards();
  updateMultiSelectBar();
}

function updateMultiSelectCards() {
  document.querySelectorAll('.item-card').forEach(card => {
    const on = multiSelected.has(card.dataset.path);
    card.classList.toggle('is-multi-selected', on);
    const cb = card.querySelector('.item-check');
    if (cb) cb.checked = on;
  });
}

function updateMultiSelectBar() {
  const bar = el('multi-select-bar');
  if (!bar) return;
  const count = multiSelected.size;
  bar.classList.toggle('hidden', count === 0);
  if (count === 0) return;
  const totalBytes = allItems
    .filter(i => multiSelected.has(i.path))
    .reduce((sum, i) => sum + (i.total_size || 0), 0);
  setText('multi-select-info', `${count} item${count > 1 ? 's' : ''} selected · ${bytesToHuman(totalBytes)}`);
}

function markMultiSelected() {
  multiSelected.forEach(path => markedItems.add(path));
  updateMarkedSidebar();
  document.querySelectorAll('.item-card').forEach(card => {
    if (!multiSelected.has(card.dataset.path)) return;
    card.classList.add('is-marked');
    const btn = card.querySelector('.mark-btn');
    if (btn) { btn.className = 'mark-btn marked'; btn.textContent = '🗑️ Marked'; }
  });
  clearMultiSelect();
  updateDetailMarkBtn();
}

function clearMultiSelect() {
  multiSelected.clear();
  lastMultiIndex = -1;
  updateMultiSelectCards();
  updateMultiSelectBar();
}

function copyFor115() {
  const names = allItems
    .filter(i => multiSelected.has(i.path) && i.bango)
    .map(i => i.bango)
    .join(' | ');
  if (!names) return;

  const btn = document.querySelector('.ms-btn-115');
  const reset = () => { if (btn) { btn.textContent = '📋 Copy for 115'; } };

  navigator.clipboard.writeText(names).then(() => {
    if (btn) { btn.textContent = '✓ Copied!'; setTimeout(reset, 1500); }
  }).catch(() => {
    // Clipboard API blocked (e.g. file:// without HTTPS) — fall back to prompt
    prompt('Copy this 115 search string (Ctrl+A, Ctrl+C):', names);
  });
}

function exportMarked() {
  if (!markedItems.size) return;
  const nameByPath = {};
  (window.__javData__?.items || []).forEach(item => { nameByPath[item.path] = item.name; });
  const lines = ['# Marked for Deletion', `# Generated: ${new Date().toISOString()}`, ''];
  for (const path of markedItems) lines.push('# ' + (nameByPath[path] ?? path));
  const blob = new Blob([lines.join('\r\n')], { type: 'text/plain;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), {
    href: url, download: `deletion_list_${new Date().toISOString().slice(0,10)}.txt`,
  });
  a.click();
  URL.revokeObjectURL(url);
}


// ─────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────

function el(id)        { return document.getElementById(id); }
function setText(id, v){ const e = el(id); if (e) e.textContent = v; }

function esc(str) {
  return String(str ?? '')
    .replace(/&/g,'&amp;').replace(/</g,'&lt;')
    .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function fmtDate(iso) {
  if (!iso) return '?';
  try {
    return new Date(iso).toLocaleString('zh-CN', {
      year:'numeric', month:'2-digit', day:'2-digit',
      hour:'2-digit', minute:'2-digit',
    });
  } catch { return iso.slice(0, 16); }
}

function bytesToHuman(b) {
  if (b <= 0) return '0 B';
  const units = ['B','KB','MB','GB','TB'];
  let i = 0;
  while (b >= 1024 && i < units.length - 1) { b /= 1024; i++; }
  return `${b.toFixed(1)} ${units[i]}`;
}

function seriesColor(name, alpha = 1) {
  let hash = 0;
  for (let i = 0; i < name.length; i++)
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  const h = Math.abs(hash) % 360;
  return `hsla(${h},70%,60%,${alpha})`;
}


// ─────────────────────────────────────────────
// Classifier
// ─────────────────────────────────────────────

function clGetCategory(item) {
  return clOverrides[item.path] ?? classifyMap[item.path] ?? null;
}

function clCountsByCat() {
  const counts = Object.fromEntries(CL_CATS.map(c => [c, 0]));
  counts.all = allItems.length;
  allItems.forEach(item => {
    const cat = clGetCategory(item);
    if (cat && counts[cat] !== undefined) counts[cat]++;
    else counts.unclassified++;
  });
  return counts;
}

function clSizeByCat() {
  const sizes = Object.fromEntries(CL_CATS.map(c => [c, 0]));
  sizes.all = allItems.reduce((s, i) => s + (i.total_size || 0), 0);
  allItems.forEach(item => {
    const cat = clGetCategory(item);
    const sz  = item.total_size || 0;
    if (cat && sizes[cat] !== undefined) sizes[cat] += sz;
    else sizes.unclassified += sz;
  });
  return sizes;
}

function buildClCatBar() {
  const counts = clCountsByCat();
  const bar = el('cl-cat-bar');
  if (!bar) return;
  bar.innerHTML = '';
  CL_CATS.forEach(cat => {
    if (counts[cat] === 0 && cat !== 'all') return;
    const pill = document.createElement('button');
    pill.className   = 'cat-pill' + (cat === currentClCat ? ' active' : '');
    pill.dataset.cat = cat;
    const label = cat === 'all' ? 'All' : cat.charAt(0).toUpperCase() + cat.slice(1);
    pill.innerHTML = `${CL_ICONS[cat] ?? '🗂️'} ${label}<span class="pill-count">${counts[cat]}</span>`;
    pill.onclick = () => { currentClCat = cat; refreshClCatBar(); renderClList(); };
    bar.appendChild(pill);
  });
}

function refreshClCatBar() {
  const counts = clCountsByCat();
  document.querySelectorAll('#cl-cat-bar .cat-pill').forEach(pill => {
    const cat = pill.dataset.cat;
    pill.classList.toggle('active', cat === currentClCat);
    const span = pill.querySelector('.pill-count');
    if (span) span.textContent = counts[cat] ?? 0;
  });
}

function buildClStatsBar() {
  const counts = clCountsByCat();
  const sizes  = clSizeByCat();
  const bar = el('cl-stats-bar');
  if (!bar) return;
  bar.innerHTML = '';
  CL_CATS.filter(c => c !== 'all' && c !== 'unclassified' && counts[c] > 0).forEach(cat => {
    const chip = document.createElement('div');
    chip.className = 'cl-stat-chip';
    const color = CL_COLORS[cat] || '#90a4ae';
    chip.innerHTML = `
      <div class="chip-val" style="color:${color}">${counts[cat]}</div>
      <div class="chip-lbl">${CL_ICONS[cat] ?? ''} ${cat}</div>
      <div class="chip-size">${bytesToHuman(sizes[cat])}</div>`;
    bar.appendChild(chip);
  });
}

function renderClassifier() {
  // Header labels
  const timeEl = el('cl-time');
  const modEl  = el('cl-model-label');
  if (timeEl) timeEl.textContent = clTime ? 'Updated ' + clTime.slice(0, 16) : '';
  if (modEl)  modEl.textContent  = hasClassifyData ? `model: ${clModel}` : '';

  // Not-ready banner
  const banner = el('cl-not-ready');
  if (banner) banner.classList.toggle('hidden', hasClassifyData);

  if (!hasClassifyData) {
    el('cl-stats-bar').innerHTML = '';
    el('cl-cat-bar').innerHTML   = '';
    el('cl-list').innerHTML      = '';
    return;
  }

  buildClStatsBar();
  buildClCatBar();
  renderClList();
}

function renderClList() {
  if (!hasClassifyData) return;
  const query = (el('cl-search')?.value || '').toLowerCase().trim();

  const items = allItems.filter(item => {
    const cat = clGetCategory(item);
    const matchCat =
      currentClCat === 'all'          ? true :
      currentClCat === 'unclassified' ? !cat :
      cat === currentClCat;
    if (!matchCat) return false;
    if (query) {
      const hay = (item.name + ' ' + (item.bango || '') + ' ' + (item.title || '')).toLowerCase();
      return hay.includes(query);
    }
    return true;
  });

  // Share filteredItems so range-select and markMultiSelected work in this view
  filteredItems  = items;
  lastMultiIndex = -1;

  const totalSize = items.reduce((s, i) => s + (i.total_size || 0), 0);
  const rb = el('cl-result-bar');
  if (rb) rb.textContent = `${items.length} item${items.length !== 1 ? 's' : ''} · ${bytesToHuman(totalSize)}`;

  const list = el('cl-list');
  if (!list) return;

  // Helper: build one classifier card (base card + cat badge + override btn)
  function makeClCard(item, idx) {
    const card = createItemCard(item, idx);

    // Insert classifier category badge right after the checkbox col (before series badge)
    const cat = clGetCategory(item) ?? 'unclassified';
    const catBadge = document.createElement('div');
    catBadge.className   = `cl-cat-badge ${cat}`;
    catBadge.textContent = (CL_ICONS[cat] ?? '') + ' ' + cat;
    card.insertBefore(catBadge, card.children[1]);   // index 0 = checkbox, 1 = thumb/info

    // Override button — cycles category (session-only)
    const btn = document.createElement('button');
    btn.className   = 'cl-override-btn';
    btn.title       = 'Cycle category (session only)';
    btn.textContent = '✎';
    btn.onclick = e => {
      e.stopPropagation();
      const cur  = clGetCategory(item) ?? 'other';
      const next = CL_CYCLE[(CL_CYCLE.indexOf(cur) + 1) % CL_CYCLE.length];
      clOverrides[item.path] = next;
      catBadge.className   = `cl-cat-badge ${next}`;
      catBadge.textContent = (CL_ICONS[next] ?? '') + ' ' + next;
      refreshClCatBar();
      buildClStatsBar();
    };
    card.appendChild(btn);
    return card;
  }

  // Lazy-load in pages
  disconnectClObserver();
  clOffset = 0;
  list.innerHTML = '';

  function appendNextClPage() {
    const end  = Math.min(clOffset + BROWSE_PAGE, items.length);
    const frag = document.createDocumentFragment();
    for (let i = clOffset; i < end; i++) {
      frag.appendChild(makeClCard(items[i], i));
    }
    clOffset = end;

    const old = list.querySelector('.browse-sentinel');
    if (old) old.remove();

    list.appendChild(frag);

    if (clOffset < items.length) {
      const sentinel = document.createElement('div');
      sentinel.className = 'browse-sentinel';
      list.appendChild(sentinel);

      clObserver = new IntersectionObserver(entries => {
        if (entries[0].isIntersecting) {
          disconnectClObserver();
          appendNextClPage();
        }
      }, { rootMargin: '300px' });
      clObserver.observe(sentinel);
    }
  }

  appendNextClPage();
}
