/* ═══════════════════════════════════════════════════
   JAV Manager — Frontend Application
   Data source: data.js (generated by scan.py)
   Javbus info: direct iframe — no server needed
   ═══════════════════════════════════════════════════ */

'use strict';


// ─────────────────────────────────────────────
// State
// ─────────────────────────────────────────────

let appData        = null;
let allItems       = [];
let filteredItems  = [];
let markedItems    = new Set();
let multiSelected  = new Set();   // paths currently multi-selected
let lastMultiIndex = -1;          // index in filteredItems of last Ctrl/Shift click
let currentView    = 'dashboard';
let selectedItem   = null;
let countChart     = null;
let sizeChart      = null;
let seriesSortKey  = 'count';
let seriesSortAsc  = false;


// ─────────────────────────────────────────────
// Bootstrap
// ─────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', init);

function init() {
  if (window.__javData__) {
    appData = window.__javData__;
    onDataReady();
  } else {
    // data.js not loaded — user needs to run scan.py first
    el('loading').classList.add('hidden');
    el('error-msg').classList.remove('hidden');
  }
}

function reloadData() {
  window.location.reload();
}

function onDataReady() {
  allItems = appData.items || [];

  const s = appData.statistics || {};
  setText('scan-time',  fmtDate(appData.scan_time));
  setText('total-size', s.total_size_human || '?');
  setText('total-dirs', s.total_items || '?');

  const nonjav = allItems.filter(i => !i.is_jav).length;
  const badge = el('nonjav-badge');
  if (nonjav > 0) { badge.textContent = nonjav; badge.style.display = ''; }
  else { badge.style.display = 'none'; }

  el('loading').classList.add('hidden');
  showView(currentView || 'dashboard');
}


// ─────────────────────────────────────────────
// View management
// ─────────────────────────────────────────────

function hideAllViews() {
  document.querySelectorAll('.view').forEach(v => v.classList.add('hidden'));
}

function showView(name) {
  hideAllViews();
  currentView = name;
  lastMultiIndex = -1;   // indices are view-specific; reset on tab switch

  const viewEl = el(`view-${name}`);
  if (viewEl) viewEl.classList.remove('hidden');

  document.querySelectorAll('.nav-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.view === name);
  });

  if      (name === 'dashboard')  renderDashboard();
  else if (name === 'browse')     renderBrowse();
  else if (name === 'statistics') renderStatistics();
  else if (name === 'nonjav')     renderNonJav();
}


// ─────────────────────────────────────────────
// Dashboard
// ─────────────────────────────────────────────

function renderDashboard() {
  if (!appData) return;
  const s = appData.statistics || {};

  setText('s-total',  s.total_items   || 0);
  setText('s-jav',    s.jav_count     || 0);
  setText('s-nonjav', s.non_jav_count || 0);
  setText('s-size',   s.total_size_human || '?');
  setText('s-series', Object.keys(s.series_count || {}).length);

  const countEntries = Object.entries(s.series_count || {}).slice(0, 20);
  renderBarChart('chart-count', countEntries.map(([k]) => k),
    countEntries.map(([, v]) => v), '# videos', countEntries.map(([k]) => k));

  const sizeData    = s.series_size || {};
  const sizeEntries = Object.entries(sizeData)
    .sort((a, b) => b[1].size - a[1].size).slice(0, 20);
  renderBarChart('chart-size', sizeEntries.map(([k]) => k),
    sizeEntries.map(([, v]) => +(v.size / 1e9).toFixed(1)), 'GB',
    sizeEntries.map(([k]) => k));
}

function renderBarChart(canvasId, labels, values, unit, colorKeys) {
  const canvas = el(canvasId);
  if (!canvas) return;

  const existing = Chart.getChart(canvas);
  if (existing) existing.destroy();

  // Fix explicit pixel size — prevents Chart.js responsive resize loop
  const w = canvas.parentElement.clientWidth || 500;
  const h = Math.max(260, labels.length * 28);
  canvas.width  = w;
  canvas.height = h;
  canvas.style.width  = w + 'px';
  canvas.style.height = h + 'px';

  new Chart(canvas, {
    type: 'bar',
    data: {
      labels,
      datasets: [{
        data:            values,
        backgroundColor: colorKeys.map(k => seriesColor(k, 0.65)),
        borderColor:     colorKeys.map(k => seriesColor(k, 1)),
        borderWidth: 1,
      }],
    },
    options: {
      animation: false,
      responsive: false,
      indexAxis: 'y',
      plugins: {
        legend: { display: false },
        tooltip: { callbacks: { label: ctx => ` ${ctx.raw} ${unit}` } },
      },
      scales: {
        x: { beginAtZero: true,
             ticks: { color: '#7070a0', font: { size: 11 } },
             grid:  { color: '#2a2a50' } },
        y: { ticks: { color: '#e0e0f0', font: { size: 11 } },
             grid:  { display: false } },
      },
    },
  });
}


// ─────────────────────────────────────────────
// Browse
// ─────────────────────────────────────────────

function renderBrowse() { applyFilters(); }

function applyFilters() {
  if (!allItems.length) return;

  const query   = (el('search-box')?.value  || '').toLowerCase().trim();
  const sort    = el('sort-select')?.value  || 'size-desc';
  const javOnly = el('jav-only')?.checked   || false;

  let items = allItems.filter(item => {
    if (javOnly && !item.is_jav) return false;
    if (query) {
      const hay = (item.name + ' ' + (item.bango || '') + ' ' +
                   (item.title || '') + ' ' + (item.actresses || []).join(' ')).toLowerCase();
      return hay.includes(query);
    }
    return true;
  });

  items.sort((a, b) => {
    switch (sort) {
      case 'size-desc':  return b.total_size - a.total_size;
      case 'size-asc':   return a.total_size - b.total_size;
      case 'name-asc':   return a.name.localeCompare(b.name);
      case 'name-desc':  return b.name.localeCompare(a.name);
      case 'series-asc': return (a.series || 'zzz').localeCompare(b.series || 'zzz');
      default:           return 0;
    }
  });

  filteredItems = items;
  setText('result-count', items.length);
  setText('result-size', bytesToHuman(items.reduce((s, i) => s + (i.total_size || 0), 0)));
  renderItemList(items, 'item-list');
}

function renderItemList(items, containerId) {
  const container = el(containerId);
  if (!container) return;
  const frag = document.createDocumentFragment();
  items.forEach((item, idx) => frag.appendChild(createItemCard(item, idx)));
  container.innerHTML = '';
  container.appendChild(frag);
}

function createItemCard(item, idx = -1) {
  const isMarked      = markedItems.has(item.path);
  const isSelected    = selectedItem && selectedItem.path === item.path;
  const isMultiSelect = multiSelected.has(item.path);

  const card = document.createElement('div');
  card.className = 'item-card' +
    (isSelected    ? ' is-selected'      : '') +
    (isMarked      ? ' is-marked'        : '') +
    (isMultiSelect ? ' is-multi-selected': '');
  card.dataset.path = item.path;

  // Checkbox for multi-select
  const checkCol = document.createElement('div');
  checkCol.className = 'item-check-col';
  const checkbox = document.createElement('input');
  checkbox.type    = 'checkbox';
  checkbox.className = 'item-check';
  checkbox.checked = isMultiSelect;
  checkbox.addEventListener('click', e => {
    e.stopPropagation();
    handleMultiClick(item, idx, e.shiftKey);
  });
  checkCol.appendChild(checkbox);
  card.appendChild(checkCol);

  // Series badge
  const badge = document.createElement('div');
  badge.className = 'item-series-badge';
  const series = item.series || '?';
  badge.textContent = series.length > 7 ? series.slice(0, 7) + '…' : series;
  badge.style.background   = item.is_jav ? seriesColor(series, 0.2)  : 'rgba(100,100,120,0.25)';
  badge.style.color        = item.is_jav ? seriesColor(series, 1)    : '#7070a0';
  badge.style.border       = `1px solid ${item.is_jav ? seriesColor(series, 0.45) : 'transparent'}`;
  card.appendChild(badge);

  // Cover thumbnail (embedded from metadata)
  if (item.cover) {
    const thumb = document.createElement('img');
    thumb.className = 'item-thumb';
    thumb.src = item.cover;
    thumb.alt = '';
    thumb.loading = 'lazy';
    thumb.onerror = function() { this.style.display = 'none'; };
    card.appendChild(thumb);
  }

  // Info — show javbus title if available, folder name as fallback/tooltip
  const actressHtml = item.actresses?.length
    ? `<div class="item-actresses">${
        item.actresses.slice(0, 3).map(a => `<span class="actress-tag">${esc(a)}</span>`).join('')
      }${item.actresses.length > 3 ? `<span class="actress-tag">+${item.actresses.length - 3}</span>` : ''}</div>`
    : '';

  const info = document.createElement('div');
  info.className = 'item-info';
  info.innerHTML = `
    <div class="item-bango">${esc(item.bango || '(no bango)')}</div>
    <div class="item-name" title="${esc(item.name)}">${esc(item.title || item.name)}</div>
    <div class="item-meta">${item.file_count} file(s) · ${item.video_count} video(s)</div>
    ${actressHtml}
  `;
  card.appendChild(info);

  // Size
  const sizeEl = document.createElement('div');
  sizeEl.className = 'item-size';
  sizeEl.textContent = item.total_size_human || '?';
  card.appendChild(sizeEl);

  // Mark button
  const markBtn = document.createElement('button');
  markBtn.className   = 'mark-btn' + (isMarked ? ' marked' : '');
  markBtn.textContent = isMarked ? '🗑️ Marked' : '🗑️ Mark';
  markBtn.onclick = e => {
    e.stopPropagation();
    toggleMark(item);
    const marked = markedItems.has(item.path);
    markBtn.className   = 'mark-btn' + (marked ? ' marked' : '');
    markBtn.textContent = marked ? '🗑️ Marked' : '🗑️ Mark';
    card.classList.toggle('is-marked', marked);
    if (selectedItem?.path === item.path) updateDetailMarkBtn();
  };
  card.appendChild(markBtn);

  card.addEventListener('click', () => openDetail(item));
  return card;
}


// ─────────────────────────────────────────────
// Statistics
// ─────────────────────────────────────────────

function renderStatistics() {
  if (!appData) return;
  const sizeData  = appData.statistics.series_size  || {};
  const countData = appData.statistics.series_count || {};

  let rows = Object.entries(countData).map(([series, count]) => ({
    series,
    count,
    size:       sizeData[series]?.size       || 0,
    size_human: sizeData[series]?.size_human || '?',
  }));

  rows.sort((a, b) => {
    let cmp = 0;
    if      (seriesSortKey === 'series') cmp = a.series.localeCompare(b.series);
    else if (seriesSortKey === 'count')  cmp = a.count - b.count;
    else if (seriesSortKey === 'size')   cmp = a.size  - b.size;
    return seriesSortAsc ? cmp : -cmp;
  });

  const tbody = el('series-body');
  tbody.innerHTML = '';

  rows.forEach((row, idx) => {
    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td class="rank-cell">${idx + 1}</td>
      <td class="series-cell">
        <span style="display:inline-block;width:10px;height:10px;border-radius:3px;
          background:${seriesColor(row.series)};margin-right:7px;vertical-align:middle"></span>
        ${esc(row.series)}
      </td>
      <td class="count-cell">${row.count}</td>
      <td class="size-cell">${row.size_human}</td>
    `;
    tr.style.cursor = 'pointer';
    tr.title = `Click to browse ${row.series}`;
    tr.addEventListener('click', () => {
      el('jav-only').checked = false;
      el('search-box').value = row.series;
      showView('browse');
    });
    tbody.appendChild(tr);
  });
}

function sortSeriesTable(key) {
  if (seriesSortKey === key) seriesSortAsc = !seriesSortAsc;
  else { seriesSortKey = key; seriesSortAsc = false; }
  renderStatistics();
}


// ─────────────────────────────────────────────
// Non-JAV
// ─────────────────────────────────────────────

function renderNonJav() {
  const items = allItems.filter(i => !i.is_jav);
  filteredItems = items;
  const totalBytes = items.reduce((sum, i) => sum + (i.total_size || 0), 0);
  const humanSize = appData?.statistics?.total_size_human
    ? (() => {
        // reuse the same formatting logic
        let b = totalBytes;
        for (const u of ['B','KB','MB','GB','TB']) {
          if (b < 1024) return b.toFixed(1) + ' ' + u;
          b /= 1024;
        }
        return b.toFixed(1) + ' PB';
      })()
    : '?';
  setText('nonjav-size', `${items.length} items · ${humanSize}`);
  renderItemList(items, 'nonjav-list');
}


// ─────────────────────────────────────────────
// Detail panel
// ─────────────────────────────────────────────

function openDetail(item) {
  selectedItem = item;
  document.querySelectorAll('.item-card').forEach(c =>
    c.classList.toggle('is-selected', c.dataset.path === item.path)
  );
  el('detail-panel').classList.remove('hidden');
  renderDetailShell(item);
}

function closeDetail() {
  el('detail-panel').classList.add('hidden');
  closeJavbus();
  selectedItem = null;
  document.querySelectorAll('.item-card.is-selected')
    .forEach(c => c.classList.remove('is-selected'));
}

function renderDetailShell(item) {
  const isMarked = markedItems.has(item.path);

  // Build metadata block from embedded fields (populated by scan.py via javbus)
  let metaHtml = '';
  if (item.is_jav && (item.cover || item.title || item.actresses?.length)) {
    const actressHtml = item.actresses?.length
      ? `<div class="jav-actresses">👤 ${item.actresses.map(a => `<span class="actress-tag">${esc(a)}</span>`).join('')}</div>`
      : '';
    metaHtml = `
      <div class="jav-info-card">
        ${item.cover ? `<img class="jav-cover" src="${esc(item.cover)}" alt="cover" loading="lazy" onerror="this.style.display='none'">` : ''}
        <div class="jav-meta">
          ${item.title ? `<div class="jav-title">${esc(item.title)}</div>` : ''}
          ${actressHtml}
        </div>
      </div>`;
  }

  el('detail-body').innerHTML = `
    <div class="detail-bango">${esc(item.bango || '(no bango)')}</div>

    ${metaHtml}

    <div class="detail-section-title">Files on disk</div>
    <div style="font-size:12px;color:var(--text-muted);margin-bottom:8px;">
      <a class="path-link" href="${localUrl(item.path)}" target="_blank" title="Open folder">📁 ${esc(item.name)}</a>
      &nbsp;·&nbsp; ${item.total_size_human} &nbsp;·&nbsp; ${item.file_count} file(s)
    </div>
    <div id="detail-files">${renderFileList(item.path, item.files)}</div>
    ${item.file_count > item.files.length
      ? `<div style="font-size:12px;color:var(--text-muted);margin-top:6px;">
           … and ${item.file_count - item.files.length} more in subfolders
         </div>` : ''}

    <div class="detail-actions">
      ${item.bango
        ? `<button class="detail-link-btn" onclick="openJavbus('${esc(item.bango)}')">
             🎬 View on Javbus
           </button>` : ''}
      <button class="detail-mark-btn ${isMarked ? 'unmark' : ''}" id="detail-mark-btn"
        onclick="toggleMarkFromDetail()">
        ${isMarked ? '↩️ Unmark' : '🗑️ Mark for Deletion'}
      </button>
    </div>
  `;
}

function renderFileList(folderPath, files) {
  if (!files?.length) return '<div class="muted">No files listed</div>';
  return files.map(f => {
    const url = localUrl(folderPath + '\\' + f.name);
    return `<div class="file-entry">
       <span>${fileIcon(f.ext)}</span>
       <a class="file-name path-link" href="${url}" target="_blank" title="${esc(f.name)}">${esc(f.name)}</a>
       <span class="file-size">${f.size_human || ''}</span>
     </div>`;
  }).join('');
}

// Convert a Windows path to a file:// URL
function localUrl(winPath) {
  return 'file:///' + winPath.replace(/\\/g, '/');
}

function fileIcon(ext) {
  const VIDEO = new Set(['.mp4','.mkv','.avi','.wmv','.mov','.m4v','.ts','.m2ts','.iso','.rmvb','.flv','.webm']);
  if (VIDEO.has(ext)) return '🎬';
  if (['.jpg','.jpeg','.png','.webp','.avif','.gif','.bmp'].includes(ext)) return '🖼️';
  if (ext === '.nfo') return '📄';
  if (['.srt','.ass','.ssa','.sub'].includes(ext)) return '💬';
  return '📎';
}

function updateDetailMarkBtn() {
  if (!selectedItem) return;
  const btn = el('detail-mark-btn');
  if (!btn) return;
  const marked = markedItems.has(selectedItem.path);
  btn.className   = 'detail-mark-btn' + (marked ? ' unmark' : '');
  btn.textContent = marked ? '↩️ Unmark' : '🗑️ Mark for Deletion';
}


// ─────────────────────────────────────────────
// Javbus iframe overlay
// ─────────────────────────────────────────────

// Javbus URL slug differs by studio:
//   1PONDO-052611-102     → 052611_102   (underscore)
//   CARIBBEANCOM-102720-001 → 102720-001  (dash)
//   everything else       → bango as-is
function javbusSlug(bango) {
  let m = bango.match(/^1PONDO-(\d{6})-(\d{3})$/i);
  if (m) return `${m[1]}_${m[2]}`;
  m = bango.match(/^(?:CARIBBEANCOM|CARIBPR)-(\d{6})-(\d{3})$/i);
  if (m) return `${m[1]}-${m[2]}`;
  return bango;
}

function openJavbus(bango) {
  const overlay = el('javbus-overlay');
  const iframe  = el('javbus-iframe');
  const bangoEl = el('javbus-bango-label');
  const link    = el('javbus-newtab');

  const slug = javbusSlug(bango);
  const url  = `https://www.javbus.com/${encodeURIComponent(slug)}`;
  if (bangoEl) bangoEl.textContent = bango;
  if (link)    link.href = url;
  iframe.src = url;
  overlay.classList.remove('hidden');
}

function closeJavbus() {
  const overlay = el('javbus-overlay');
  const iframe  = el('javbus-iframe');
  if (!overlay) return;
  overlay.classList.add('hidden');
  iframe.src = '';   // stop loading
}


// ─────────────────────────────────────────────
// Marking
// ─────────────────────────────────────────────

function toggleMark(item) {
  if (markedItems.has(item.path)) markedItems.delete(item.path);
  else markedItems.add(item.path);
  updateMarkedSidebar();
}

function toggleMarkFromDetail() {
  if (!selectedItem) return;
  toggleMark(selectedItem);
  updateDetailMarkBtn();
  const card = document.querySelector(`.item-card[data-path="${CSS.escape(selectedItem.path)}"]`);
  if (card) {
    const marked = markedItems.has(selectedItem.path);
    card.classList.toggle('is-marked', marked);
    const btn = card.querySelector('.mark-btn');
    if (btn) {
      btn.className   = 'mark-btn' + (marked ? ' marked' : '');
      btn.textContent = marked ? '🗑️ Marked' : '🗑️ Mark';
    }
  }
}

function updateMarkedSidebar() {
  const count = markedItems.size;
  const sidebar = el('marked-sidebar');
  el('marked-count').textContent = count;
  sidebar.classList.toggle('hidden', count === 0);
}

function clearMarked() {
  markedItems.clear();
  updateMarkedSidebar();
  document.querySelectorAll('.item-card.is-marked').forEach(c => {
    c.classList.remove('is-marked');
    const btn = c.querySelector('.mark-btn');
    if (btn) { btn.className = 'mark-btn'; btn.textContent = '🗑️ Mark'; }
  });
  updateDetailMarkBtn();
}

// ─────────────────────────────────────────────
// Multi-select
// ─────────────────────────────────────────────

function handleMultiClick(item, idx, isShift) {
  if (isShift && lastMultiIndex >= 0 && idx >= 0) {
    // Range select: add everything from lastMultiIndex to idx
    const from = Math.min(lastMultiIndex, idx);
    const to   = Math.max(lastMultiIndex, idx);
    for (let i = from; i <= to; i++) {
      if (filteredItems[i]) multiSelected.add(filteredItems[i].path);
    }
  } else {
    // Ctrl/⌘: toggle single item
    if (multiSelected.has(item.path)) multiSelected.delete(item.path);
    else                              multiSelected.add(item.path);
    lastMultiIndex = idx;
  }
  updateMultiSelectCards();
  updateMultiSelectBar();
}

function updateMultiSelectCards() {
  document.querySelectorAll('.item-card').forEach(card => {
    const on = multiSelected.has(card.dataset.path);
    card.classList.toggle('is-multi-selected', on);
    const cb = card.querySelector('.item-check');
    if (cb) cb.checked = on;
  });
}

function updateMultiSelectBar() {
  const bar = el('multi-select-bar');
  if (!bar) return;
  const count = multiSelected.size;
  bar.classList.toggle('hidden', count === 0);
  if (count === 0) return;
  const totalBytes = allItems
    .filter(i => multiSelected.has(i.path))
    .reduce((sum, i) => sum + (i.total_size || 0), 0);
  setText('multi-select-info', `${count} item${count > 1 ? 's' : ''} selected · ${bytesToHuman(totalBytes)}`);
}

function markMultiSelected() {
  multiSelected.forEach(path => markedItems.add(path));
  updateMarkedSidebar();
  document.querySelectorAll('.item-card').forEach(card => {
    if (!multiSelected.has(card.dataset.path)) return;
    card.classList.add('is-marked');
    const btn = card.querySelector('.mark-btn');
    if (btn) { btn.className = 'mark-btn marked'; btn.textContent = '🗑️ Marked'; }
  });
  clearMultiSelect();
  updateDetailMarkBtn();
}

function clearMultiSelect() {
  multiSelected.clear();
  lastMultiIndex = -1;
  updateMultiSelectCards();
  updateMultiSelectBar();
}

function exportMarked() {
  if (!markedItems.size) return;
  const nameByPath = {};
  (window.__javData__?.items || []).forEach(item => { nameByPath[item.path] = item.name; });
  const lines = ['# Marked for Deletion', `# Generated: ${new Date().toISOString()}`, ''];
  for (const path of markedItems) lines.push('# ' + (nameByPath[path] ?? path));
  const blob = new Blob([lines.join('\r\n')], { type: 'text/plain;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), {
    href: url, download: `deletion_list_${new Date().toISOString().slice(0,10)}.txt`,
  });
  a.click();
  URL.revokeObjectURL(url);
}


// ─────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────

function el(id)        { return document.getElementById(id); }
function setText(id, v){ const e = el(id); if (e) e.textContent = v; }

function esc(str) {
  return String(str ?? '')
    .replace(/&/g,'&amp;').replace(/</g,'&lt;')
    .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function fmtDate(iso) {
  if (!iso) return '?';
  try {
    return new Date(iso).toLocaleString('zh-CN', {
      year:'numeric', month:'2-digit', day:'2-digit',
      hour:'2-digit', minute:'2-digit',
    });
  } catch { return iso.slice(0, 16); }
}

function bytesToHuman(b) {
  if (b <= 0) return '0 B';
  const units = ['B','KB','MB','GB','TB'];
  let i = 0;
  while (b >= 1024 && i < units.length - 1) { b /= 1024; i++; }
  return `${b.toFixed(1)} ${units[i]}`;
}

function seriesColor(name, alpha = 1) {
  let hash = 0;
  for (let i = 0; i < name.length; i++)
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  const h = Math.abs(hash) % 360;
  return `hsla(${h},70%,60%,${alpha})`;
}
